PRUEBA_BRAHAN_A_ACOSTA/Models/ErrorViewModel.cs
namespace PRUEBA_BRAHAN_A_ACOSTA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PRUEBA_BRAHAN_A_ACOSTA/Models/PacienteModel.cs
using System.ComponentModel.DataAnnotations;

namespace PRUEBA_BRAHAN_A_ACOSTA.Models
{
    public class PacienteModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo tipo de documento es obligatorio")]
        public string tipoDocumento { get; set; }

        [Required(ErrorMessage = "El campo número de documento es obligatorio")]
        public string numeroDocumento { get; set; }

        [Required(ErrorMessage = "El campo nombre es obligatorio")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "El campo apellido es obligatorio")]
        public string apellidos { get; set; }

        [Required(ErrorMessage = "El campo correo es obligatorio")]
        public string correo { get; set; }

        [Required(ErrorMessage = "El campo telefono es obligatorio")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "El campo fecha de nacimiento es obligatorio")]
        public DateTime fecha_nacimiento { get; set; }

        [Required(ErrorMessage = "El campo estado es obligatorio")]
        public string estado { get; set; }
    }
}

PRUEBA_BRAHAN_A_ACOSTA/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PRUEBA_BRAHAN_A_ACOSTA.Models;
using System.Diagnostics;

namespace PRUEBA_BRAHAN_A_ACOSTA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PRUEBA_BRAHAN_A_ACOSTA/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;

using PRUEBA_BRAHAN_A_ACOSTA.Datos;
using PRUEBA_BRAHAN_A_ACOSTA.Models;

namespace PRUEBA_BRAHAN_A_ACOSTA.Controllers
{
    public class PacienteController : Controller
    {
        PacienteDatos _pacienteDatos = new PacienteDatos();
        public IActionResult Listar()
        {
            
            // VISTA DONDE MUESTRA LA LISTA DE PACIENTES
            var oLista = _pacienteDatos.Listar();
            return View(oLista);
        }

        public IActionResult Guardar()
        {
            // METODO DONDE DEVUELVE LA VISTA
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(PacienteModel opaciente)
        {
            // METODO PARA GUARDAR EL OBJETO EN BD
            if (!ModelState.IsValid)
                return View();

            var respuesta = _pacienteDatos.Guardar(opaciente);

            if (respuesta)
                return RedirectToAction("Listar");
            else
            return View();
        }

        public IActionResult Editar(int Id)
        {
            var opaciente = _pacienteDatos.obtener(Id);
            return View(opaciente);
        }

        [HttpPost]
        public IActionResult Editar(PacienteModel opaciente)
        {
            // METODO PARA EDITAR EL OBJETO EN BD
            if (!ModelState.IsValid)
                return View();

            var respuesta = _pacienteDatos.Editar(opaciente);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int Id)
        {
            var opaciente = _pacienteDatos.obtener(Id);
            return View(opaciente);
        }

        [HttpPost]
        public IActionResult Eliminar(PacienteModel opaciente)
        {
            // METODO PARA ELIMINAR EL OBJETO EN BD

            var respuesta = _pacienteDatos.Eliminar(opaciente.Id);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }
    }
}

PRUEBA_BRAHAN_A_ACOSTA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PRUEBA_BRAHAN_A_ACOSTA/Views/Paciente/Editar.cshtml
@model PacienteModel

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Editar contacto</h5>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Paciente" method="post">
            <input asp-for="Id" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Tipo de documento</label>
                <input asp-for="tipoDocumento" type="text" class="form-control">
                <span asp-validation-for="tipoDocumento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Número de documento</label>
                <input asp-for="numeroDocumento" type="text" class="form-control">
                <span asp-validation-for="numeroDocumento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombres" type="text" class="form-control">
                <span asp-validation-for="nombres" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellidos" type="text" class="form-control">
                <span asp-validation-for="apellidos" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo electronico</label>
                <input asp-for="correo" type="text" class="form-control">
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="telefono" type="text" class="form-control">
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de nacimiento</label>
                <input asp-for="fecha_nacimiento" type="date" class="form-control">
                <span asp-validation-for="fecha_nacimiento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Estado de afiliación</label>
                <input asp-for="estado" type="text" class="form-control">
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
            <a asp-action="Listar" asp-controller="Paciente" class="btn btn-warning ">Volver a la lista</a>
        </form>
    </div>
</div>

PRUEBA_BRAHAN_A_ACOSTA/Views/Paciente/Eliminar.cshtml
@model PacienteModel

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Eliminar contacto</h5>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Paciente" method="post">
            <input asp-for="Id" type="hidden" class="form-control">
            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar el contacto: @Html.DisplayTextFor(m => m.nombres)?
            </div>
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Paciente" class="btn btn-warning ">Volver a la lista</a>
        </form>
    </div>
</div>

PRUEBA_BRAHAN_A_ACOSTA/Views/Paciente/Guardar.cshtml
@model PacienteModel

@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Crear contacto</h5>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Paciente" method="post">
            <div class="mb-3">
                <label class="form-label">Tipo de documento</label>
                <input asp-for="tipoDocumento" type="text" class="form-control">
                <span asp-validation-for="tipoDocumento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Número de documento</label>
                <input asp-for="numeroDocumento" type="text" class="form-control">
                <span asp-validation-for="numeroDocumento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombres" type="text" class="form-control">
                <span asp-validation-for="nombres" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Apellidos</label>
                <input asp-for="apellidos" type="text" class="form-control">
                <span asp-validation-for="apellidos" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo electronico</label>
                <input asp-for="correo" type="text" class="form-control">
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="telefono" type="text" class="form-control">
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Fecha de nacimiento</label>
                <input asp-for="fecha_nacimiento" type="date" class="form-control">
                <span asp-validation-for="fecha_nacimiento" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Estado de afiliación</label>
                <input asp-for="estado" type="text" class="form-control">
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Paciente" class="btn btn-warning ">Volver a la lista</a>
        </form>
    </div>
</div>

PRUEBA_BRAHAN_A_ACOSTA/Views/Paciente/Listar.cshtml
@model List<PacienteModel>;

@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Lista de pacientes</h5>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Paciente" class="btn btn-success ">Crear nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tipo de documento</th>
                    <th>Número de documento</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Correo</th>
                    <th>Telefono</th>
                    <th>Fecha de nacimiento</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.tipoDocumento</td>
                        <td>@item.numeroDocumento</td>
                        <td>@item.nombres</td>
                        <td>@item.apellidos</td>
                        <td>@item.correo</td>
                        <td>@item.telefono</td>
                        <td>@item.fecha_nacimiento</td>
                        <td>@item.estado</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Paciente" class="btn btn-primary btn-sm" asp-route-id="@item.Id">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Paciente" class="btn btn-danger btn-sm" asp-route-id="@item.Id">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PRUEBA_BRAHAN_A_ACOSTA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRUEBA_BRAHAN_A_ACOSTA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRUEBA_BRAHAN_A_ACOSTA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRUEBA_BRAHAN_A_ACOSTA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PRUEBA_BRAHAN_A_ACOSTA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>